name: Remind Appointments

on:
schedule:
- cron: "*/5 * * * *"
workflow_dispatch:

env:
SUPA_FN_URL: ${{ vars.SUPA_FN_URL }}
CRON_SECRET: ${{ secrets.CRON_SECRET }}

jobs:
trigger-reminder:
runs-on: ubuntu-latest
steps:
- name: Invoke remind-appointments function
run: |
set -eo pipefail
if [ -z "${SUPA_FN_URL:-}" ]; then
echo "Environment variable SUPA_FN_URL is not set." >&2
exit 1
fi
if [ -z "${CRON_SECRET:-}" ]; then
echo "Secret CRON_SECRET is not set." >&2
exit 1
fi
response_file="remind-appointments-response.json"
url="${SUPA_FN_URL%/}/remind-appointments?key=${CRON_SECRET}"
status=$(curl -sS -o "$response_file" -w "%{http_code}"
-X POST "$url"
-H "Content-Type: application/json"
-d '{}')
echo "HTTP status: $status"
echo "Response body:"
cat "$response_file"
echo "Response saved to $response_file"
{
echo "## remind-appointments invocation"
echo ""
echo "- HTTP status: $status"
echo ""
echo "Response body:"
echo 'json' cat "$response_file" echo ''
} >> "$GITHUB_STEP_SUMMARY"
if [ "$status" -ne 200 ]; then
exit 1
fi