# .github/workflows/remind-appointments.yml
name: Remind Appointments (every 5 min)

on:
  schedule:
    - cron: "*/5 * * * *"   # her 5 dakikada bir (UTC)
  workflow_dispatch:        # elle tetiklemek için

jobs:
  trigger-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Edge Function and print response
        shell: bash
        run: |
          set -euo pipefail
          URL="${{ vars.SUPA_FN_URL }}?key=${{ secrets.CRON_SECRET }}"
          echo "POST $URL"

          HTTP_STATUS=$(curl -sS -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            -o /tmp/res.json \
            -w '%{http_code}' \
            "$URL")

          echo "HTTP_STATUS=$HTTP_STATUS"
          echo "Response body:"
          cat /tmp/res.json

          {
            echo "### remind-appointments response"
            echo
            echo "**HTTP:** $HTTP_STATUS"
            echo
            echo '```json'
            cat /tmp/res.json
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

          if [ "$HTTP_STATUS" != "200" ]; then
            exit 1
          fi
